import Navbar from "@/components/ui/navbar";
import type { Metadata } from "next";
import { Saira } from "next/font/google";

import "./globals.css";
import Providers from "./providers";

const saira = Saira({
  subsets: ["latin"],
  variable: "--font-saira",
  weight: ["700", "600", "500", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${saira.variable} antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <footer className="min-h-20 border-t border-white/10 outline-2 outline-offset-4 outline-white/10 flex items-center p-4">
            <p className="mx-auto text-7xl uppercase font-bold bg-gradient-to-b from-white via-white/10 to-black from bg-clip-text text-transparent opacity-25">
              Liquid Arena
            </p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
